services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LIBFPRINT_DSC_URL: "http://archive.ubuntu.com/ubuntu/pool/main/libf/libfprint/libfprint_1.94.7+tod1-0ubuntu4.dsc"
        GOODIX_REPO_URL: "https://git.launchpad.net/libfprint-2-tod1-goodix"
        GOODIX_BRANCH: "ubuntu/noble-devel"
    container_name: goodix-tod-builder
    volumes:
      - ./out:/out
    environment:
      # GPG verification of the .dsc (0 = verify, 1 = skip verification)
      - DGET_NO_CHECK=${DGET_NO_CHECK:-0}
      # Debianized version (defaults below can be overridden via .env)
      - DEBIAN_DIST=${DEBIAN_DIST:-trixie}
      - DEBIAN_REV=${DEBIAN_REV:-0}
      - DEBIAN_LOCAL=${DEBIAN_LOCAL:-~trixie1}
      # - DEBIAN_FORCE_VERSION=1:1.94.7+tod1-1~trixie1
      - DEBIAN_FRONTEND=noninteractive
    command: ["/bin/bash", "/build.sh"]
