services:
  goodix-tod-builder:
    build:
      context: .
      dockerfile: Dockerfile
    image: goodix-tod-build
    environment:
      LIBFPRINT_DSC_URL: "http://archive.ubuntu.com/ubuntu/pool/main/libf/libfprint/libfprint_1.94.7+tod1-0ubuntu4.dsc"
      GOODIX_REPO_URL: "https://git.launchpad.net/libfprint-2-tod1-goodix"
      GOODIX_BRANCH: "ubuntu/noble-devel"
      DGET_NO_CHECK: "0"   # keep signature verification ON
      DIST_NAME: "trixie"
      LOCAL_SUFFIX: "~trixie1"
    volumes:
      - ./out:/out
    tty: true
